export const DATA = [
  {
    headshot_url: "202307191/images/headshots/5/5ccf29ba_sabr.jpg",
    id: "abreu-001bob",
    link: "/players/a/abreubo01.shtml",
    name: "Bobby Abreu",
    name_first: "Bobby",
    name_last: "Abreu",
    search_name: ["Bobby Abreu"],
    teams: [
      { id: "NYM" },
      { id: "LAD" },
      { id: "ANA", season_b_rbi_100: "qualified", season_b_sb_30: "qualified" },
      {
        id: "NYY",
        season_b_avg_300: "qualified",
        season_b_rbi_100: "qualified",
      },
      {
        id: "PHI",
        season_allstar: "qualified",
        season_award_gold_glove: "qualified",
        season_award_silver_slugger: "qualified",
        season_b_avg_300: "qualified",
        season_b_hr_30_sb_30: "qualified",
        season_b_rbi_100: "qualified",
        season_b_sb_30: "qualified",
      },
      { id: "HOU" },
    ],
    years: "1996-2014",
  },
  {
    career_p_sv_300: "unqualified",
    headshot_url: "202307191/images/headshots/c/c29fd34b_sabr.jpg",
    id: "aguile001ric",
    link: "/players/a/aguilri01.shtml",
    name: "Rick Aguilera",
    name_first: "Rick",
    name_last: "Aguilera",
    search_name: ["Rick Aguilera"],
    teams: [
      {
        id: "MIN",
        season_allstar: "qualified",
        season_p_sv_40: "qualified",
        ws_champ: "qualified",
      },
      { id: "NYM", ws_champ: "qualified" },
      { id: "CHC" },
      { id: "BOS" },
    ],
    years: "1985-2000",
  },
];
