export const DATA = [
  {
    id: "abreu-001bob",
    teams: [
      { id: "NYM" },
      { id: "LAD" },
      { id: "ANA", season_b_rbi_100: 1, season_b_sb_30: 1 },
      { id: "NYY", season_b_rbi_100: 1 },
      {
        id: "PHI",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_sb_30: 1,
        season_award_gold_glove: 1,
        season_award_silver_slugger: 1,
        season_b_hr_30_sb_30: 1,
      },
      { id: "HOU" },
    ],
    name: "Bobby Abreu",
    name_first: "Bobby",
    name_last: "Abreu",
    years: "1996-2014",
    headshot_url: "202307191/images/headshots/5/5ccf29ba_sabr.jpg",
    search_name: ["Bobby Abreu"],
    link: "/players/a/abreubo01.shtml",
  },
  {
    id: "aguile001ric",
    teams: [
      { id: "MIN", season_allstar: 1, season_p_sv_40: 1, ws_champ: 1 },
      { id: "NYM", ws_champ: 1 },
      { id: "CHC" },
      { id: "BOS" },
    ],
    name: "Rick Aguilera",
    name_first: "Rick",
    name_last: "Aguilera",
    years: "1985-2000",
    headshot_url: "202307191/images/headshots/c/c29fd34b_sabr.jpg",
    search_name: ["Rick Aguilera"],
    link: "/players/a/aguilri01.shtml",
    career_p_sv_300: 1,
  },
  {
    id: "allen-001eth",
    teams: [
      { id: "CHC" },
      { id: "CIN", season_b_avg_300: 1 },
      { id: "SFG" },
      { id: "PHI", season_b_avg_300: 1 },
      { id: "BAL", season_b_avg_300: 1 },
      { id: "STL" },
    ],
    name: "Ethan Allen",
    name_first: "Ethan",
    name_last: "Allen",
    years: "1926-1938",
    headshot_url: "202307191/images/headshots/a/ace19da3_sabr.jpg",
    search_name: ["Ethan Allen"],
    link: "/players/a/allenet01.shtml",
  },
  {
    id: "alomar001rob",
    teams: [
      { id: "ARI" },
      { id: "NYM" },
      { id: "SDP", season_allstar: 1, season_b_sb_30: 1 },
      {
        id: "CLE",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_sb_30: 1,
        season_award_gold_glove: 1,
        season_award_silver_slugger: 1,
      },
      {
        id: "BAL",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_award_gold_glove: 1,
        season_award_silver_slugger: 1,
      },
      { id: "CHW" },
      {
        id: "TOR",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_sb_30: 1,
        season_award_gold_glove: 1,
        season_award_silver_slugger: 1,
        ws_champ: 1,
      },
    ],
    name: "Roberto Alomar",
    name_first: "Roberto",
    name_last: "Alomar",
    years: "1988-2004",
    headshot_url: "202307191/images/headshots/2/24c918e7_sabr.jpg",
    search_name: ["Roberto Alomar"],
    link: "/players/a/alomaro01.shtml",
    career_b_avg_300: 1,
    career_award_hof: 1,
  },
  {
    id: "alou--001mat",
    teams: [
      { id: "SDP" },
      { id: "PIT", season_allstar: 1, season_b_avg_300: 1, season_b_h_200: 1 },
      { id: "SFG" },
      { id: "NYY" },
      { id: "STL", season_b_avg_300: 1 },
      { id: "OAK", ws_champ: 1 },
    ],
    name: "Matty Alou",
    name_first: "Matty",
    name_last: "Alou",
    years: "1960-1974",
    headshot_url: "202307191/images/headshots/3/3d8b257b_sabr.jpg",
    search_name: ["Matty Alou"],
    link: "/players/a/alouma01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "alou--001moi",
    teams: [
      { id: "NYM" },
      { id: "CHC", season_allstar: 1, season_b_rbi_100: 1 },
      {
        id: "WSN",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_award_silver_slugger: 1,
      },
      { id: "SFG", season_allstar: 1 },
      { id: "PIT" },
      {
        id: "HOU",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_award_silver_slugger: 1,
      },
      { id: "FLA", season_allstar: 1, season_b_rbi_100: 1, ws_champ: 1 },
    ],
    name: "Moises Alou",
    name_first: "Moises",
    name_last: "Alou",
    years: "1990-2008",
    headshot_url: "202307191/images/headshots/3/30ebdf88_sabr.jpg",
    search_name: ["Moises Alou"],
    link: "/players/a/aloumo01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "baines001har",
    teams: [
      { id: "TEX", season_allstar: 1, season_award_silver_slugger: 1 },
      { id: "CLE", season_allstar: 1 },
      { id: "BAL", season_allstar: 1 },
      { id: "OAK", season_allstar: 1 },
      {
        id: "CHW",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_award_silver_slugger: 1,
      },
    ],
    name: "Harold Baines",
    name_first: "Harold",
    name_last: "Baines",
    years: "1980-2001",
    headshot_url: "202307191/images/headshots/8/8e1285e8_sabr.jpg",
    search_name: ["Harold Baines"],
    link: "/players/b/baineha01.shtml",
    career_award_hof: 1,
  },
  {
    id: "bancro001dav",
    teams: [
      { id: "LAD" },
      { id: "SFG", season_b_avg_300: 1, season_b_h_200: 1, ws_champ: 1 },
      { id: "ATL", season_b_avg_300: 1 },
      { id: "PHI" },
    ],
    name: "Dave Bancroft",
    name_first: "Dave",
    name_last: "Bancroft",
    years: "1915-1930",
    headshot_url: "202307191/images/headshots/8/8822919c_sabr.jpg",
    search_name: ["Dave Bancroft"],
    link: "/players/b/bancrda01.shtml",
    career_award_hof: 1,
  },
  {
    id: "baylor001don",
    teams: [
      { id: "MIN", ws_champ: 1 },
      {
        id: "ANA",
        season_allstar: 1,
        season_b_rbi_100: 1,
        season_award_mvp: 1,
      },
      { id: "NYY", season_b_avg_300: 1, season_award_silver_slugger: 1 },
      { id: "BAL", season_b_sb_30: 1 },
      { id: "BOS", season_award_silver_slugger: 1 },
      { id: "OAK", season_b_sb_30: 1 },
    ],
    name: "Don Baylor",
    name_first: "Don",
    name_last: "Baylor",
    years: "1970-1988",
    headshot_url: "202307191/images/headshots/d/dbdccbfa_sabr.jpg",
    search_name: ["Don Baylor"],
    link: "/players/b/baylodo01.shtml",
  },
  {
    id: "beckle001jac",
    teams: [
      { id: "CIN", season_b_avg_300: 1 },
      { id: "PBB", season_b_avg_300: 1, season_b_rbi_100: 1 },
      { id: "SFG" },
      {
        id: "PIT",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_sb_30: 1,
      },
      { id: "STL", season_b_avg_300: 1 },
    ],
    name: "Jake Beckley",
    name_first: "Jake",
    name_last: "Beckley",
    years: "1888-1907",
    headshot_url: "202307191/images/headshots/b/b2aa2e3e_sabr.jpg",
    search_name: ["Jake Beckley"],
    link: "/players/b/becklja01.shtml",
    career_b_avg_300: 1,
    career_award_hof: 1,
  },
  {
    id: "beltra001car",
    teams: [
      {
        id: "KCR",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_sb_30: 1,
        season_award_roty: 1,
      },
      { id: "TEX", season_allstar: 1 },
      {
        id: "NYM",
        season_allstar: 1,
        season_b_rbi_100: 1,
        season_b_hr_40: 1,
        season_award_gold_glove: 1,
        season_award_silver_slugger: 1,
      },
      { id: "SFG", season_allstar: 1 },
      { id: "NYY", season_allstar: 1 },
      { id: "STL", season_allstar: 1 },
      { id: "HOU", season_allstar: 1, ws_champ: 1 },
    ],
    name: "Carlos Beltr\u00e1n",
    name_first: "Carlos",
    name_last: "Beltr\u00e1n",
    years: "1998-2017",
    headshot_url: "202307191/images/headshots/f/fa0f9b5c_sabr.jpg",
    search_name: ["Carlos Beltran"],
    link: "/players/b/beltrca01.shtml",
  },
  {
    id: "beltre001adr",
    teams: [
      {
        id: "TEX",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_award_gold_glove: 1,
        season_award_silver_slugger: 1,
      },
      {
        id: "LAD",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_b_hr_40: 1,
        season_award_silver_slugger: 1,
      },
      { id: "SEA", season_award_gold_glove: 1 },
      {
        id: "BOS",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_award_silver_slugger: 1,
      },
    ],
    name: "Adri\u00e1n Beltr\u00e9",
    name_first: "Adri\u00e1n",
    name_last: "Beltr\u00e9",
    years: "1998-2018",
    headshot_url: "202307191/images/headshots/1/1423362b_sabr_sea.jpg",
    search_name: ["Adrian Beltre"],
    link: "/players/b/beltrad01.shtml",
    career_b_h_3000: 1,
  },
  {
    id: "benite001arm",
    teams: [
      { id: "NYM", season_allstar: 1, season_p_sv_40: 1 },
      { id: "SFG" },
      { id: "SEA", season_allstar: 1 },
      { id: "NYY", season_allstar: 1 },
      { id: "FLA", season_allstar: 1, season_p_sv_40: 1 },
      { id: "BAL" },
      { id: "TOR" },
    ],
    name: "Armando Ben\u00edtez",
    name_first: "Armando",
    name_last: "Ben\u00edtez",
    years: "1994-2008",
    headshot_url: "202307191/images/headshots/4/47f7f822_sabr.jpg",
    search_name: ["Armando Benitez"],
    link: "/players/b/benitar01.shtml",
  },
  {
    id: "blylev001rik",
    teams: [
      {
        id: "MIN",
        season_allstar: 1,
        season_p_w_20: 1,
        season_p_so_200: 1,
        ws_champ: 1,
      },
      { id: "TEX" },
      { id: "ANA" },
      { id: "CLE", season_allstar: 1 },
      { id: "PIT", ws_champ: 1 },
    ],
    name: "Bert Blyleven",
    name_first: "Bert",
    name_last: "Blyleven",
    years: "1970-1992",
    headshot_url: "202307191/images/headshots/8/86826f24_sabr.jpg",
    search_name: ["Bert Blyleven"],
    link: "/players/b/blylebe01.shtml",
    career_p_so_3000: 1,
    career_award_hof: 1,
  },
  {
    id: "bonds-001bob",
    teams: [
      {
        id: "SFG",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_b_sb_30: 1,
        season_award_gold_glove: 1,
        season_b_hr_30_sb_30: 1,
      },
      { id: "STL" },
      { id: "TEX", season_b_sb_30: 1 },
      {
        id: "ANA",
        season_b_rbi_100: 1,
        season_b_sb_30: 1,
        season_b_hr_30_sb_30: 1,
      },
      { id: "CLE", season_b_sb_30: 1 },
      { id: "CHC" },
      {
        id: "NYY",
        season_allstar: 1,
        season_b_sb_30: 1,
        season_b_hr_30_sb_30: 1,
      },
      { id: "CHW" },
    ],
    name: "Bobby Bonds",
    name_first: "Bobby",
    name_last: "Bonds",
    years: "1968-1981",
    headshot_url: "202307191/images/headshots/5/5af0e0b0_sabr.jpg",
    search_name: ["Bobby Bonds"],
    link: "/players/b/bondsbo01.shtml",
  },
  {
    id: "bonill001rob",
    teams: [
      { id: "NYM", season_allstar: 1 },
      {
        id: "PIT",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_award_silver_slugger: 1,
      },
      { id: "ATL" },
      { id: "STL" },
      { id: "LAD" },
      { id: "BAL", season_allstar: 1, season_b_rbi_100: 1 },
      { id: "FLA", ws_champ: 1 },
      { id: "CHW" },
    ],
    name: "Bobby Bonilla",
    name_first: "Bobby",
    name_last: "Bonilla",
    years: "1986-2001",
    headshot_url: "202307191/images/headshots/0/065291f6_sabr.jpg",
    search_name: ["Bobby Bonilla"],
    link: "/players/b/bonilbo01.shtml",
  },
  {
    id: "bonura001hen",
    teams: [
      { id: "MIN", season_b_rbi_100: 1 },
      { id: "CHC" },
      { id: "SFG", season_b_avg_300: 1 },
      { id: "CHW", season_b_avg_300: 1, season_b_rbi_100: 1 },
    ],
    name: "Zeke Bonura",
    name_first: "Zeke",
    name_last: "Bonura",
    years: "1934-1940",
    headshot_url: "202307191/images/headshots/9/972fe435_sabr.jpg",
    search_name: ["Zeke Bonura"],
    link: "/players/b/bonurze01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "bressl001ray",
    teams: [
      { id: "LAD", season_b_avg_300: 1 },
      { id: "CIN", season_b_avg_300: 1, ws_champ: 1 },
      { id: "PHI" },
      { id: "STL" },
      { id: "OAK" },
    ],
    name: "Rube Bressler",
    name_first: "Rube",
    name_last: "Bressler",
    years: "1914-1932",
    headshot_url: "202307191/images/headshots/5/57364bc9_sabr.jpg",
    search_name: ["Rube Bressler"],
    link: "/players/b/bressru01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "brouth001den",
    teams: [
      { id: "LOU" },
      { id: "TRT" },
      { id: "BUF", season_b_avg_300: 1 },
      { id: "SFG" },
      { id: "PHI" },
      { id: "ATL", season_b_avg_300: 1, season_b_rbi_100: 1 },
      {
        id: "BLO",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_sb_30: 1,
      },
      {
        id: "BRS",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_sb_30: 1,
      },
      {
        id: "LAD",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_sb_30: 1,
      },
      {
        id: "DTN",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_sb_30: 1,
      },
    ],
    name: "Dan Brouthers",
    name_first: "Dan",
    name_last: "Brouthers",
    years: "1879-1904",
    headshot_url: "202307191/images/headshots/c/c08044f6_sabr.jpg",
    search_name: ["Dan Brouthers"],
    link: "/players/b/broutda01.shtml",
    career_b_avg_300: 1,
    career_award_hof: 1,
  },
  {
    id: "bunnin001jam",
    teams: [
      { id: "LAD" },
      { id: "PIT" },
      { id: "PHI", season_allstar: 1, season_p_so_200: 1 },
      { id: "DET", season_allstar: 1, season_p_w_20: 1, season_p_so_200: 1 },
    ],
    name: "Jim Bunning",
    name_first: "Jim",
    name_last: "Bunning",
    years: "1955-1971",
    headshot_url: "202307191/images/headshots/b/bcacaa59_sabr_phi.jpg",
    search_name: ["Jim Bunning"],
    link: "/players/b/bunniji01.shtml",
    career_award_hof: 1,
  },
  {
    id: "burket001jes",
    teams: [
      { id: "SFG", season_b_avg_300: 1 },
      { id: "BAL", season_b_avg_300: 1 },
      { id: "STL", season_b_avg_300: 1, season_b_h_200: 1, season_b_sb_30: 1 },
      { id: "BOS" },
      { id: "CLV", season_b_avg_300: 1, season_b_h_200: 1, season_b_sb_30: 1 },
    ],
    name: "Jesse Burkett",
    name_first: "Jesse",
    name_last: "Burkett",
    years: "1890-1905",
    headshot_url: "202307191/images/headshots/5/53d6808e_sabr.jpg",
    search_name: ["Jesse Burkett"],
    link: "/players/b/burkeje01.shtml",
    career_b_avg_300: 1,
    career_award_hof: 1,
  },
  {
    id: "burns-001geo",
    teams: [
      {
        id: "CLE",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_award_mvp: 1,
        ws_champ: 1,
      },
      { id: "NYY" },
      { id: "DET" },
      { id: "BOS", season_b_avg_300: 1 },
      { id: "OAK", season_b_avg_300: 1, ws_champ: 1 },
    ],
    name: "George Burns",
    name_first: "George",
    name_last: "Burns",
    years: "1914-1929",
    headshot_url: "202307191/images/headshots/8/88e2067e_sabr.jpg",
    search_name: ["George Burns"],
    link: "/players/b/burnsge02.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "bush--001les",
    teams: [
      { id: "MIN" },
      { id: "SFG" },
      { id: "PIT" },
      { id: "NYY", season_p_w_20: 1, ws_champ: 1 },
      { id: "BAL" },
      { id: "BOS", ws_champ: 1 },
      { id: "OAK", ws_champ: 1 },
    ],
    name: "Bullet Joe Bush",
    name_first: "Bullet Joe",
    name_last: "Bush",
    years: "1912-1928",
    headshot_url: "202307191/images/headshots/3/30a2a3bd_sabr.jpg",
    search_name: ["Bullet Joe Bush"],
    link: "/players/b/bushjo01.shtml",
  },
  {
    id: "butler001bre",
    teams: [
      { id: "NYM" },
      { id: "LAD", season_allstar: 1, season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "CLE", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "SFG", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "ATL", season_b_sb_30: 1 },
    ],
    name: "Brett Butler",
    name_first: "Brett",
    name_last: "Butler",
    years: "1981-1997",
    headshot_url: "202307191/images/headshots/4/41366870_sabr.jpg",
    search_name: ["Brett Butler"],
    link: "/players/b/butlebr01.shtml",
  },
  {
    id: "cano--001rob",
    teams: [
      { id: "NYM" },
      { id: "SDP" },
      { id: "ATL" },
      {
        id: "SEA",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
      },
      {
        id: "NYY",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_award_gold_glove: 1,
        season_award_silver_slugger: 1,
        ws_champ: 1,
      },
    ],
    name: "Robinson Can\u00f3",
    name_first: "Robinson",
    name_last: "Can\u00f3",
    years: "2005-2022",
    headshot_url: "202307191/images/headshots/a/ae57de14_sabr_nyy.jpg",
    search_name: ["Robinson Cano"],
    link: "/players/c/canoro01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "carden001jos",
    teams: [
      { id: "KCR" },
      { id: "NYM" },
      { id: "SFG" },
      { id: "PHI" },
      { id: "STL" },
      { id: "ANA", season_b_sb_30: 1 },
      { id: "CLE", season_b_sb_30: 1 },
      { id: "CHC", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "MIL" },
    ],
    name: "Jos\u00e9 Cardenal",
    name_first: "Jos\u00e9",
    name_last: "Cardenal",
    years: "1963-1980",
    headshot_url: "202307191/images/headshots/8/8a7502e4_sabr.jpg",
    search_name: ["Jose Cardenal"],
    link: "/players/c/cardejo02.shtml",
  },
  {
    id: "carlto001ste",
    teams: [
      { id: "MIN" },
      { id: "CLE" },
      { id: "SFG" },
      {
        id: "PHI",
        season_allstar: 1,
        season_p_w_20: 1,
        season_p_so_200: 1,
        season_award_gold_glove: 1,
        season_award_cy_young: 1,
        ws_champ: 1,
      },
      {
        id: "STL",
        season_allstar: 1,
        season_p_w_20: 1,
        season_p_so_200: 1,
        ws_champ: 1,
      },
      { id: "CHW" },
    ],
    name: "Steve Carlton",
    name_first: "Steve",
    name_last: "Carlton",
    years: "1965-1988",
    headshot_url: "202307191/images/headshots/e/e438064d_sabr.jpg",
    search_name: ["Steve Carlton"],
    link: "/players/c/carltst01.shtml",
    career_p_w_300: 1,
    career_p_so_3000: 1,
    career_award_hof: 1,
  },
  {
    id: "carter002gar",
    teams: [
      { id: "LAD" },
      {
        id: "NYM",
        season_allstar: 1,
        season_b_rbi_100: 1,
        season_award_silver_slugger: 1,
        ws_champ: 1,
      },
      {
        id: "WSN",
        season_allstar: 1,
        season_b_rbi_100: 1,
        season_award_gold_glove: 1,
        season_award_silver_slugger: 1,
      },
      { id: "SFG" },
    ],
    name: "Gary Carter",
    name_first: "Gary",
    name_last: "Carter",
    years: "1974-1992",
    headshot_url: "202307191/images/headshots/1/1a995e9e_sabr.jpg",
    search_name: ["Gary Carter"],
    link: "/players/c/cartega01.shtml",
    career_award_hof: 1,
  },
  {
    id: "carter001jos",
    teams: [
      { id: "SDP", season_b_rbi_100: 1 },
      {
        id: "CLE",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_b_sb_30: 1,
        season_b_hr_30_sb_30: 1,
      },
      { id: "CHC" },
      { id: "SFG" },
      { id: "BAL" },
      {
        id: "TOR",
        season_allstar: 1,
        season_b_rbi_100: 1,
        season_award_silver_slugger: 1,
        ws_champ: 1,
      },
    ],
    name: "Joe Carter",
    name_first: "Joe",
    name_last: "Carter",
    years: "1983-1998",
    headshot_url: "202307191/images/headshots/d/d6d37272_sabr.jpg",
    search_name: ["Joe Carter"],
    link: "/players/c/cartejo01.shtml",
  },
  {
    id: "cepeda001orl",
    teams: [
      { id: "KCR" },
      {
        id: "SFG",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_hr_40: 1,
        season_award_roty: 1,
      },
      { id: "ATL", season_b_avg_300: 1, season_b_rbi_100: 1 },
      {
        id: "STL",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_award_mvp: 1,
        ws_champ: 1,
      },
      { id: "BOS" },
      { id: "OAK" },
    ],
    name: "Orlando Cepeda",
    name_first: "Orlando",
    name_last: "Cepeda",
    years: "1958-1974",
    headshot_url: "202307191/images/headshots/0/017440d1_sabr.jpg",
    search_name: ["Orlando Cepeda"],
    link: "/players/c/cepedor01.shtml",
    career_award_hof: 1,
  },
  {
    id: "cesped000yoe",
    teams: [
      {
        id: "NYM",
        season_allstar: 1,
        season_award_gold_glove: 1,
        season_award_silver_slugger: 1,
      },
      { id: "DET", season_award_gold_glove: 1 },
      { id: "BOS", season_allstar: 1 },
      { id: "OAK", season_allstar: 1 },
    ],
    name: "Yoenis C\u00e9spedes",
    name_first: "Yoenis",
    name_last: "C\u00e9spedes",
    years: "2012-2020",
    headshot_url: "202307191/images/headshots/b/b1b973f3_mlbam.jpg",
    search_name: ["Yoenis Cespedes"],
    link: "/players/c/cespeyo01.shtml",
  },
  {
    id: "chapma001aro",
    teams: [
      { id: "KCR" },
      { id: "TEX" },
      { id: "CHC", ws_champ: 1 },
      { id: "CIN", season_allstar: 1 },
      { id: "NYY", season_allstar: 1 },
    ],
    name: "Aroldis Chapman",
    name_first: "Aroldis",
    name_last: "Chapman",
    years: "2010-2023",
    headshot_url: "202307191/images/headshots/e/e7d0cac7_mlbam.jpg",
    search_name: ["Aroldis Chapman"],
    link: "/players/c/chapmar01.shtml",
    career_p_sv_300: 1,
  },
  {
    id: "chapma002wil",
    teams: [
      { id: "MIN", season_allstar: 1 },
      { id: "LAD" },
      { id: "CLE" },
      { id: "PHI" },
      {
        id: "NYY",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_sb_30: 1,
        ws_champ: 1,
      },
      { id: "CHW" },
      { id: "BOS", season_b_avg_300: 1 },
    ],
    name: "Ben Chapman",
    name_first: "Ben",
    name_last: "Chapman",
    years: "1930-1946",
    headshot_url: "202307191/images/headshots/0/0fe7f158_sabr.jpg",
    search_name: ["Ben Chapman"],
    link: "/players/c/chapmbe01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "clark-007wil",
    teams: [
      {
        id: "TEX",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
      },
      {
        id: "SFG",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_award_gold_glove: 1,
        season_award_silver_slugger: 1,
      },
      { id: "STL" },
      { id: "BAL" },
    ],
    name: "Will Clark",
    name_first: "Will",
    name_last: "Clark",
    years: "1986-2000",
    headshot_url: "202307191/images/headshots/3/3bcff907_sabr.jpg",
    search_name: ["Will Clark"],
    link: "/players/c/clarkwi02.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "griffi003cla",
    teams: [
      { id: "MIN" },
      { id: "BRS" },
      { id: "CIN" },
      { id: "CHC", season_p_w_20: 1 },
      { id: "NYY" },
      { id: "STL" },
      { id: "CHW", season_p_w_20: 1 },
    ],
    name: "Clark Griffith",
    name_first: "Clark",
    name_last: "Griffith",
    years: "1891-1914",
    headshot_url: "202307191/images/headshots/9/96624988_sabr.jpg",
    search_name: ["Clark Griffith"],
    link: "/players/g/griffcl01.shtml",
    career_award_hof: 1,
  },
  {
    id: "clemen001wil",
    teams: [
      {
        id: "NYY",
        season_allstar: 1,
        season_p_w_20: 1,
        season_p_so_200: 1,
        season_award_cy_young: 1,
        ws_champ: 1,
      },
      {
        id: "HOU",
        season_allstar: 1,
        season_p_so_200: 1,
        season_award_cy_young: 1,
      },
      {
        id: "TOR",
        season_allstar: 1,
        season_p_w_20: 1,
        season_p_so_200: 1,
        season_award_cy_young: 1,
      },
      {
        id: "BOS",
        season_allstar: 1,
        season_p_w_20: 1,
        season_p_so_200: 1,
        season_award_mvp: 1,
        season_award_cy_young: 1,
      },
    ],
    name: "Roger Clemens",
    name_first: "Roger",
    name_last: "Clemens",
    years: "1984-2007",
    headshot_url: "202307191/images/headshots/b/b5a2be2f_br.jpg",
    search_name: ["Roger Clemens"],
    link: "/players/c/clemero02.shtml",
    career_p_w_300: 1,
    career_p_so_3000: 1,
  },
  {
    id: "colavi001roc",
    teams: [
      { id: "LAD" },
      {
        id: "CLE",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_hr_40: 1,
      },
      { id: "NYY" },
      { id: "DET", season_allstar: 1, season_b_rbi_100: 1, season_b_hr_40: 1 },
      { id: "CHW" },
      { id: "OAK", season_allstar: 1, season_b_rbi_100: 1 },
    ],
    name: "Rocky Colavito",
    name_first: "Rocky",
    name_last: "Colavito",
    years: "1955-1968",
    headshot_url: "202307191/images/headshots/8/8899e413_sabr.jpg",
    search_name: ["Rocky Colavito"],
    link: "/players/c/colavro01.shtml",
  },
  {
    id: "colema002vin",
    teams: [
      { id: "KCR", season_b_sb_30: 1 },
      { id: "NYM", season_b_sb_30: 1 },
      { id: "CIN" },
      { id: "SEA" },
      { id: "DET" },
      { id: "STL", season_allstar: 1, season_b_sb_30: 1, season_award_roty: 1 },
    ],
    name: "Vince Coleman",
    name_first: "Vince",
    name_last: "Coleman",
    years: "1985-1997",
    headshot_url: "202307191/images/headshots/7/78c1d3e9_sabr.jpg",
    search_name: ["Vince Coleman"],
    link: "/players/c/colemvi01.shtml",
  },
  {
    id: "collin001dav",
    teams: [
      { id: "STL" },
      { id: "OAK" },
      { id: "ANA", season_b_sb_30: 1 },
      { id: "CIN", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "SEA" },
      { id: "NYY" },
      { id: "DET" },
      { id: "TOR", season_b_sb_30: 1 },
    ],
    name: "Dave Collins",
    name_first: "Dave",
    name_last: "Collins",
    years: "1975-1990",
    headshot_url: "202307191/images/headshots/a/ab0c8e4e_sabr.jpg",
    search_name: ["Dave Collins"],
    link: "/players/c/collida02.shtml",
  },
  {
    id: "colon-001bar",
    teams: [
      { id: "MIN" },
      { id: "NYM", season_allstar: 1 },
      { id: "ATL" },
      { id: "OAK", season_allstar: 1 },
      { id: "BOS" },
      { id: "TEX" },
      { id: "CLE", season_allstar: 1, season_p_so_200: 1 },
      { id: "WSN" },
      {
        id: "ANA",
        season_allstar: 1,
        season_p_w_20: 1,
        season_award_cy_young: 1,
      },
      { id: "NYY" },
      { id: "CHW" },
    ],
    name: "Bartolo Colon",
    name_first: "Bartolo",
    name_last: "Colon",
    years: "1997-2018",
    headshot_url: "202307191/images/headshots/1/1625da35_br.jpg",
    search_name: ["Bartolo Colon"],
    link: "/players/c/colonba01.shtml",
  },
  {
    id: "cone--001dav",
    teams: [
      { id: "KCR", season_allstar: 1, season_award_cy_young: 1 },
      { id: "NYM", season_allstar: 1, season_p_w_20: 1, season_p_so_200: 1 },
      {
        id: "NYY",
        season_allstar: 1,
        season_p_w_20: 1,
        season_p_so_200: 1,
        ws_champ: 1,
      },
      { id: "BOS" },
      { id: "TOR", season_allstar: 1, ws_champ: 1 },
    ],
    name: "David Cone",
    name_first: "David",
    name_last: "Cone",
    years: "1986-2003",
    headshot_url: "202307191/images/headshots/1/191828e7_sabr.jpg",
    search_name: ["David Cone"],
    link: "/players/c/coneda01.shtml",
  },
  {
    id: "cooper008wil",
    teams: [
      { id: "CHC" },
      { id: "CIN", season_allstar: 1 },
      { id: "PIT" },
      {
        id: "SFG",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
      },
      { id: "ATL", season_allstar: 1 },
      { id: "STL", season_allstar: 1, season_b_avg_300: 1, ws_champ: 1 },
    ],
    name: "Walker Cooper",
    name_first: "Walker",
    name_last: "Cooper",
    years: "1940-1957",
    headshot_url: "202307191/images/headshots/d/dceb1250_sabr.jpg",
    search_name: ["Walker Cooper"],
    link: "/players/c/coopewa01.shtml",
  },
  {
    id: "corder001fra",
    teams: [
      { id: "TEX", season_allstar: 1, season_p_sv_40: 1 },
      { id: "CIN", season_allstar: 1, season_p_sv_40: 1 },
      { id: "HOU" },
      { id: "DET" },
      { id: "TOR" },
      { id: "MIL", season_allstar: 1, season_p_sv_40: 1 },
    ],
    name: "Francisco Cordero",
    name_first: "Francisco",
    name_last: "Cordero",
    years: "1999-2012",
    headshot_url: "202307191/images/headshots/1/160932d7_sabr.jpg",
    search_name: ["Francisco Cordero"],
    link: "/players/c/cordefr01.shtml",
    career_p_sv_300: 1,
  },
  {
    id: "covele001sta",
    teams: [
      { id: "MIN", season_p_w_20: 1 },
      { id: "CLE", season_p_w_20: 1, ws_champ: 1 },
      { id: "NYY" },
      { id: "OAK" },
    ],
    name: "Stan Coveleski",
    name_first: "Stan",
    name_last: "Coveleski",
    years: "1912-1928",
    headshot_url: "202307191/images/headshots/7/7b589446_davis.jpg",
    search_name: ["Stan Coveleski"],
    link: "/players/c/covelst01.shtml",
    career_award_hof: 1,
  },
  {
    id: "cruz--002nel",
    teams: [
      {
        id: "MIN",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_hr_40: 1,
        season_award_silver_slugger: 1,
      },
      { id: "TBD", season_allstar: 1 },
      { id: "TEX", season_allstar: 1 },
      { id: "SDP" },
      { id: "WSN" },
      {
        id: "SEA",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_hr_40: 1,
        season_award_silver_slugger: 1,
      },
      { id: "BAL", season_allstar: 1, season_b_rbi_100: 1, season_b_hr_40: 1 },
      { id: "MIL" },
    ],
    name: "Nelson Cruz",
    name_first: "Nelson",
    name_last: "Cruz",
    years: "2005-2023",
    headshot_url: "202307191/images/headshots/f/fea2f131_mlbam.jpg",
    search_name: ["Nelson Cruz"],
    link: "/players/c/cruzne02.shtml",
  },
  {
    id: "cuccin001ant",
    teams: [
      { id: "LAD", season_allstar: 1 },
      { id: "CIN", season_b_avg_300: 1 },
      { id: "SFG" },
      { id: "ATL", season_allstar: 1, season_b_avg_300: 1 },
      { id: "CHW", season_allstar: 1, season_b_avg_300: 1 },
    ],
    name: "Tony Cuccinello",
    name_first: "Tony",
    name_last: "Cuccinello",
    years: "1930-1945",
    headshot_url: "202307191/images/headshots/b/be5d770b_sabr.jpg",
    search_name: ["Tony Cuccinello"],
    link: "/players/c/cuccito01.shtml",
  },
  {
    id: "cuyler001haz",
    teams: [
      { id: "LAD" },
      { id: "CIN", season_b_avg_300: 1 },
      {
        id: "CHC",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_b_sb_30: 1,
      },
      {
        id: "PIT",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_b_sb_30: 1,
        ws_champ: 1,
      },
    ],
    name: "Kiki Cuyler",
    name_first: "Kiki",
    name_last: "Cuyler",
    years: "1921-1938",
    headshot_url: "202307191/images/headshots/7/7107706b_sabr.jpg",
    search_name: ["Kiki Cuyler"],
    link: "/players/c/cuyleki01.shtml",
    career_b_avg_300: 1,
    career_award_hof: 1,
  },
  {
    id: "damon-002joh",
    teams: [
      { id: "KCR", season_b_avg_300: 1, season_b_h_200: 1, season_b_sb_30: 1 },
      { id: "TBD" },
      { id: "CLE" },
      { id: "NYY", season_b_avg_300: 1, ws_champ: 1 },
      { id: "DET" },
      {
        id: "BOS",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_sb_30: 1,
        ws_champ: 1,
      },
      { id: "OAK" },
    ],
    name: "Johnny Damon",
    name_first: "Johnny",
    name_last: "Damon",
    years: "1995-2012",
    headshot_url: "202307191/images/headshots/7/7a7bca43_sabr.jpg",
    search_name: ["Johnny Damon"],
    link: "/players/d/damonjo01.shtml",
  },
  {
    id: "darvis001yu-",
    teams: [
      { id: "LAD", season_allstar: 1 },
      { id: "TEX", season_allstar: 1, season_p_so_200: 1 },
      { id: "SDP", season_allstar: 1 },
      { id: "CHC", season_p_so_200: 1 },
    ],
    name: "Yu Darvish",
    name_first: "Yu",
    name_last: "Darvish",
    years: "2012-2023",
    headshot_url: "202307191/images/headshots/5/5efb6f1a_mlbam.jpg",
    search_name: ["Yu Darvish"],
    link: "/players/d/darviyu01.shtml",
  },
  {
    id: "davis-013cha",
    teams: [
      { id: "KCR" },
      { id: "MIN", ws_champ: 1 },
      {
        id: "ANA",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
      },
      { id: "SFG", season_allstar: 1, season_b_avg_300: 1 },
      { id: "NYY", ws_champ: 1 },
    ],
    name: "Chili Davis",
    name_first: "Chili",
    name_last: "Davis",
    years: "1981-1999",
    headshot_url: "202307191/images/headshots/f/f842dfbd_sabr.jpg",
    search_name: ["Chili Davis"],
    link: "/players/d/davisch01.shtml",
  },
  {
    id: "davis-001raj",
    teams: [
      { id: "NYM" },
      { id: "SFG" },
      { id: "PIT" },
      { id: "BOS" },
      { id: "OAK", season_b_sb_30: 1 },
      { id: "CLE", season_b_sb_30: 1 },
      { id: "DET", season_b_sb_30: 1 },
      { id: "TOR", season_b_sb_30: 1 },
    ],
    name: "Rajai Davis",
    name_first: "Rajai",
    name_last: "Davis",
    years: "2006-2019",
    headshot_url: "202307191/images/headshots/8/8d0f172a_br.jpg",
    search_name: ["Rajai Davis"],
    link: "/players/d/davisra01.shtml",
  },
  {
    id: "davis-003her",
    teams: [
      { id: "KCR" },
      { id: "NYM", season_b_avg_300: 1 },
      { id: "OAK" },
      {
        id: "LAD",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        ws_champ: 1,
      },
      { id: "ANA" },
      { id: "CHC" },
      { id: "HOU" },
      { id: "BAL", season_b_avg_300: 1 },
      { id: "CHW" },
      { id: "MIL" },
    ],
    name: "Tommy Davis",
    name_first: "Tommy",
    name_last: "Davis",
    years: "1959-1976",
    headshot_url: "202307191/images/headshots/6/664f669f_sabr.jpg",
    search_name: ["Tommy Davis"],
    link: "/players/d/davisto02.shtml",
  },
  {
    id: "davis-001vir",
    teams: [
      { id: "CIN" },
      { id: "PIT" },
      { id: "PHI", season_b_avg_300: 1 },
      { id: "STL", season_b_avg_300: 1, ws_champ: 1 },
    ],
    name: "Virgil Davis",
    name_first: "Virgil",
    name_last: "Davis",
    years: "1928-1945",
    headshot_url: "202307191/images/headshots/c/cd894376_sabr.jpg",
    search_name: ["Virgil Davis"],
    link: "/players/d/davissp01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "demont001eug",
    teams: [
      { id: "MIN" },
      { id: "PIT" },
      { id: "ATL" },
      { id: "WAS", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "BLO", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "LAD" },
      { id: "CHC" },
      { id: "BAL" },
    ],
    name: "Gene DeMontreville",
    name_first: "Gene",
    name_last: "DeMontreville",
    years: "1894-1904",
    headshot_url: "202307191/images/headshots/6/633b5823_sabr.jpg",
    search_name: ["Gene DeMontreville"],
    link: "/players/d/demonge01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "donlin001mic",
    teams: [
      { id: "CIN", season_b_avg_300: 1 },
      { id: "PIT" },
      {
        id: "SFG",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_b_sb_30: 1,
        ws_champ: 1,
      },
      { id: "ATL" },
      { id: "STL" },
      { id: "BLA", season_b_avg_300: 1, season_b_sb_30: 1 },
    ],
    name: "Mike Donlin",
    name_first: "Mike",
    name_last: "Donlin",
    years: "1899-1914",
    headshot_url: "202307191/images/headshots/3/3b51e847_sabr.jpg",
    search_name: ["Mike Donlin"],
    link: "/players/d/donlimi01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "donova001pat",
    teams: [
      { id: "MIN" },
      { id: "LOU", season_b_avg_300: 1 },
      { id: "LAD" },
      { id: "PIT", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "WAS" },
      { id: "ATL" },
      { id: "STL", season_b_avg_300: 1, season_b_sb_30: 1 },
    ],
    name: "Patsy Donovan",
    name_first: "Patsy",
    name_last: "Donovan",
    years: "1890-1907",
    headshot_url: "202307191/images/headshots/7/753652af_sabr.jpg",
    search_name: ["Patsy Donovan"],
    link: "/players/d/donovpa01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "duffy-001hug",
    teams: [
      {
        id: "BRS",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_sb_30: 1,
      },
      { id: "CHC", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "PHI" },
      {
        id: "ATL",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_b_sb_30: 1,
      },
      { id: "BAL" },
      { id: "CHP", season_b_avg_300: 1, season_b_sb_30: 1 },
    ],
    name: "Hugh Duffy",
    name_first: "Hugh",
    name_last: "Duffy",
    years: "1888-1906",
    headshot_url: "202307191/images/headshots/d/d208fb41_sabr.jpg",
    search_name: ["Hugh Duffy"],
    link: "/players/d/duffyhu01.shtml",
    career_b_avg_300: 1,
    career_award_hof: 1,
  },
  {
    id: "duroch001leo",
    teams: [
      { id: "LAD", season_allstar: 1 },
      { id: "CIN" },
      { id: "NYY", ws_champ: 1 },
      { id: "STL", season_allstar: 1, ws_champ: 1 },
    ],
    name: "Leo Durocher",
    name_first: "Leo",
    name_last: "Durocher",
    years: "1925-1945",
    headshot_url: "202307191/images/headshots/3/35d925c7_sabr.jpg",
    search_name: ["Leo Durocher"],
    link: "/players/d/durocle01.shtml",
    career_award_hof: 1,
  },
  {
    id: "eckers001den",
    teams: [
      { id: "CHC" },
      { id: "CLE", season_allstar: 1, season_p_so_200: 1 },
      { id: "STL" },
      {
        id: "OAK",
        season_allstar: 1,
        season_p_sv_40: 1,
        season_award_mvp: 1,
        season_award_cy_young: 1,
        ws_champ: 1,
      },
      { id: "BOS", season_allstar: 1, season_p_w_20: 1 },
    ],
    name: "Dennis Eckersley",
    name_first: "Dennis",
    name_last: "Eckersley",
    years: "1975-1998",
    headshot_url: "202307191/images/headshots/9/98aaf620_sabr.jpg",
    search_name: ["Dennis Eckersley"],
    link: "/players/e/eckerde01.shtml",
    career_p_sv_300: 1,
    career_award_hof: 1,
  },
  {
    id: "everet001car",
    teams: [
      { id: "NYM" },
      {
        id: "BOS",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
      },
      { id: "TEX", season_allstar: 1 },
      { id: "WSN" },
      { id: "SEA" },
      { id: "FLA" },
      { id: "HOU", season_b_avg_300: 1, season_b_rbi_100: 1 },
      { id: "CHW", season_allstar: 1, ws_champ: 1 },
    ],
    name: "Carl Everett",
    name_first: "Carl",
    name_last: "Everett",
    years: "1993-2006",
    headshot_url: "202307191/images/headshots/7/7e48602e_sabr.jpg",
    search_name: ["Carl Everett"],
    link: "/players/e/evereca01.shtml",
  },
  {
    id: "evers-002joh",
    teams: [
      { id: "CHC", season_b_avg_300: 1, season_b_sb_30: 1, ws_champ: 1 },
      { id: "PHI" },
      { id: "ATL", season_award_mvp: 1, ws_champ: 1 },
      { id: "CHW" },
    ],
    name: "Johnny Evers",
    name_first: "Johnny",
    name_last: "Evers",
    years: "1902-1929",
    headshot_url: "202307191/images/headshots/e/efe76f7c_sabr.jpg",
    search_name: ["Johnny Evers"],
    link: "/players/e/eversjo01.shtml",
    career_award_hof: 1,
  },
  {
    id: "ferrel001wes",
    teams: [
      { id: "MIN", season_allstar: 1 },
      { id: "LAD" },
      { id: "CLE", season_allstar: 1, season_p_w_20: 1 },
      { id: "ATL" },
      { id: "NYY", ws_champ: 1 },
      { id: "BOS", season_allstar: 1, season_p_w_20: 1 },
    ],
    name: "Wes Ferrell",
    name_first: "Wes",
    name_last: "Ferrell",
    years: "1927-1941",
    headshot_url: "202307191/images/headshots/8/81a7570e_sabr.jpg",
    search_name: ["Wes Ferrell"],
    link: "/players/f/ferrewe01.shtml",
  },
  {
    id: "finley001ste",
    teams: [
      {
        id: "ARI",
        season_allstar: 1,
        season_b_rbi_100: 1,
        season_award_gold_glove: 1,
        ws_champ: 1,
      },
      { id: "COL" },
      { id: "SFG" },
      { id: "LAD", season_award_gold_glove: 1 },
      {
        id: "SDP",
        season_allstar: 1,
        season_b_sb_30: 1,
        season_award_gold_glove: 1,
      },
      { id: "ANA" },
      { id: "BAL" },
      { id: "HOU", season_b_sb_30: 1 },
    ],
    name: "Steve Finley",
    name_first: "Steve",
    name_last: "Finley",
    years: "1989-2007",
    headshot_url: "202307191/images/headshots/b/b60ed164_sabr.jpg",
    search_name: ["Steve Finley"],
    link: "/players/f/finlest01.shtml",
  },
  {
    id: "fonsec001lew",
    teams: [
      {
        id: "CLE",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
      },
      { id: "CIN" },
      { id: "PHI", season_b_avg_300: 1 },
      { id: "CHW" },
    ],
    name: "Lew Fonseca",
    name_first: "Lew",
    name_last: "Fonseca",
    years: "1921-1933",
    headshot_url: "202307191/images/headshots/e/ef9f81a8_sabr.jpg",
    search_name: ["Lew Fonseca"],
    link: "/players/f/fonsele01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "fourni001joh",
    teams: [
      { id: "LAD", season_b_avg_300: 1, season_b_rbi_100: 1 },
      { id: "ATL" },
      { id: "NYY" },
      { id: "STL", season_b_avg_300: 1 },
      { id: "CHW", season_b_avg_300: 1 },
    ],
    name: "Jack Fournier",
    name_first: "Jack",
    name_last: "Fournier",
    years: "1912-1927",
    headshot_url: "202307191/images/headshots/8/81af331c_sabr.jpg",
    search_name: ["Jack Fournier"],
    link: "/players/f/fournja01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "foxx--001jam",
    teams: [
      { id: "CHC" },
      { id: "PHI" },
      {
        id: "BOS",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_hr_40: 1,
        season_award_mvp: 1,
      },
      {
        id: "OAK",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_b_hr_40: 1,
        season_award_mvp: 1,
        ws_champ: 1,
      },
    ],
    name: "Jimmie Foxx",
    name_first: "Jimmie",
    name_last: "Foxx",
    years: "1925-1945",
    headshot_url: "202307191/images/headshots/e/e34a045d_sabr.jpg",
    search_name: ["Jimmie Foxx"],
    link: "/players/f/foxxji01.shtml",
    career_b_avg_300: 1,
    career_b_hr_500: 1,
    career_award_hof: 1,
  },
  {
    id: "franco001jul",
    teams: [
      { id: "NYM" },
      { id: "TBD" },
      { id: "ATL" },
      { id: "PHI" },
      {
        id: "TEX",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_h_200: 1,
        season_b_sb_30: 1,
        season_award_silver_slugger: 1,
      },
      {
        id: "CLE",
        season_b_avg_300: 1,
        season_b_sb_30: 1,
        season_award_silver_slugger: 1,
      },
      { id: "CHW", season_b_avg_300: 1, season_award_silver_slugger: 1 },
      { id: "MIL" },
    ],
    name: "Julio Franco",
    name_first: "Julio",
    name_last: "Franco",
    years: "1982-2007",
    headshot_url: "202307191/images/headshots/a/ade5464a_sabr.jpg",
    search_name: ["Julio Franco"],
    link: "/players/f/francju01.shtml",
  },
  {
    id: "galarr001and",
    teams: [
      { id: "TEX" },
      { id: "ANA" },
      {
        id: "COL",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_hr_40: 1,
        season_award_silver_slugger: 1,
      },
      {
        id: "WSN",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_award_gold_glove: 1,
        season_award_silver_slugger: 1,
      },
      { id: "SFG" },
      {
        id: "ATL",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_hr_40: 1,
      },
      { id: "STL" },
    ],
    name: "Andr\u00e9s Galarraga",
    name_first: "Andr\u00e9s",
    name_last: "Galarraga",
    years: "1985-2004",
    headshot_url: "202307191/images/headshots/4/4fa68f08_sabr.jpg",
    search_name: ["Andres Galarraga"],
    link: "/players/g/galaran01.shtml",
  },
  {
    id: "garcia006ant",
    teams: [
      { id: "LAD", season_allstar: 1, season_b_avg_300: 1 },
      { id: "CHC" },
      { id: "OAK" },
      {
        id: "BOS",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_award_silver_slugger: 1,
        season_award_roty: 1,
      },
    ],
    name: "Nomar Garciaparra",
    name_first: "Nomar",
    name_last: "Garciaparra",
    years: "1996-2009",
    headshot_url: "202307191/images/headshots/f/fb90e442_sabr.jpg",
    search_name: ["Nomar Garciaparra"],
    link: "/players/g/garcino01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "gleaso002wil",
    teams: [
      {
        id: "SFG",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_sb_30: 1,
      },
      { id: "PHI", season_p_w_20: 1, season_p_so_200: 1 },
      { id: "DET", season_b_sb_30: 1 },
      { id: "BLO", season_b_avg_300: 1 },
      { id: "STL", season_p_w_20: 1 },
      { id: "CHW" },
    ],
    name: "Kid Gleason",
    name_first: "Kid",
    name_last: "Gleason",
    years: "1888-1912",
    headshot_url: "202307191/images/headshots/6/632ed912_sabr.jpg",
    search_name: ["Kid Gleason"],
    link: "/players/g/gleaski01.shtml",
  },
  {
    id: "goodwi001tho",
    teams: [
      { id: "KCR", season_b_sb_30: 1 },
      { id: "TEX", season_b_sb_30: 1 },
      { id: "LAD" },
      { id: "CHC" },
      { id: "COL", season_b_sb_30: 1 },
      { id: "SFG" },
    ],
    name: "Tom Goodwin",
    name_first: "Tom",
    name_last: "Goodwin",
    years: "1991-2004",
    headshot_url: "202307191/images/headshots/e/ec2327e7_sabr.jpg",
    search_name: ["Tom Goodwin"],
    link: "/players/g/goodwto01.shtml",
  },
  {
    id: "gordon001tho",
    teams: [
      { id: "ARI" },
      { id: "KCR" },
      { id: "PHI", season_allstar: 1 },
      { id: "BOS", season_allstar: 1, season_p_sv_40: 1 },
      { id: "CHC" },
      { id: "NYY", season_allstar: 1 },
      { id: "HOU" },
      { id: "CHW" },
    ],
    name: "Tom Gordon",
    name_first: "Tom",
    name_last: "Gordon",
    years: "1988-2009",
    headshot_url: "202307191/images/headshots/7/7ca4573b_sabr.jpg",
    search_name: ["Tom Gordon"],
    link: "/players/g/gordoto01.shtml",
  },
  {
    id: "gossag001ric",
    teams: [
      { id: "SFG" },
      { id: "PIT", season_allstar: 1 },
      { id: "OAK" },
      { id: "TEX" },
      { id: "SDP", season_allstar: 1 },
      { id: "CHC" },
      { id: "SEA" },
      { id: "NYY", season_allstar: 1, ws_champ: 1 },
      { id: "CHW", season_allstar: 1 },
    ],
    name: "Rich Gossage",
    name_first: "Rich",
    name_last: "Gossage",
    years: "1972-1994",
    headshot_url: "202307191/images/headshots/0/0871f3e2_sabr.jpg",
    search_name: ["Rich Gossage"],
    link: "/players/g/gossari01.shtml",
    career_p_sv_300: 1,
    career_award_hof: 1,
  },
];
