export const DATA = [
  /*
  {
    id: "hernan007rob",
    teams: [
      { id: "KCR" },
      { id: "NYM" },
      { id: "TBD", season_allstar: 1, season_p_sv_40: 1 },
      { id: "PIT" },
      { id: "SFG" },
      { id: "PHI" },
      { id: "ATL" },
      { id: "LAD" },
      { id: "CLE" },
      { id: "CHW", season_allstar: 1 },
    ],
    name: "Roberto Hern\u00e1ndez",
    name_first: "Roberto",
    name_last: "Hern\u00e1ndez",
    years: "1991-2007",
    headshot_url: "202307191/images/headshots/2/2f097db1_sabr.jpg",
    search_name: ["Roberto Hernandez"],
    link: "/players/h/hernaro01.shtml",
    career_p_sv_300: 1,
  },
  {
    id: "higham001dic",
    teams: [
      { id: "TRT" },
      { id: "PRO", season_b_avg_300: 1 },
      { id: "NNA", season_b_avg_300: 1 },
      { id: "HAR", season_b_avg_300: 1 },
      { id: "CNA" },
      { id: "BLC", season_b_avg_300: 1 },
    ],
    name: "Dick Higham",
    name_first: "Dick",
    name_last: "Higham",
    years: "1871-1880",
    headshot_url: "202307191/images/headshots/8/80be8b6b_sabr.jpg",
    search_name: ["Dick Higham"],
    link: "/players/h/highadi01.shtml",
  },
  {
    id: "hines-001pau",
    teams: [
      { id: "PRO", season_b_avg_300: 1 },
      { id: "PIT" },
      { id: "WAS" },
      { id: "ATL" },
      { id: "NAT" },
      { id: "CNA", season_b_avg_300: 1 },
      { id: "WBL", season_b_avg_300: 1 },
      { id: "WNL", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "CHC", season_b_avg_300: 1 },
      { id: "IND", season_b_avg_300: 1, season_b_sb_30: 1 },
    ],
    name: "Paul Hines",
    name_first: "Paul",
    name_last: "Hines",
    years: "1872-1891",
    headshot_url: "202307191/images/headshots/c/c4e6042d_sabr.jpg",
    search_name: ["Paul Hines"],
    link: "/players/h/hinespa01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "holdsw001jim",
    teams: [
      { id: "TRT" },
      { id: "PWS", season_b_avg_300: 1 },
      { id: "IHO" },
      { id: "NNA", season_b_avg_300: 1 },
      { id: "CFC", season_b_avg_300: 1 },
      { id: "NYU" },
      { id: "ECK" },
      { id: "HAR" },
    ],
    name: "Jim Holdsworth",
    name_first: "Jim",
    name_last: "Holdsworth",
    years: "1872-1884",
    search_name: ["Jim Holdsworth"],
    link: "/players/h/holdsji01.shtml",
  },
  {
    id: "holmes003jam",
    teams: [
      { id: "MIN" },
      { id: "LOU" },
      { id: "SFG", season_b_sb_30: 1 },
      { id: "DET", season_b_sb_30: 1 },
      { id: "STL" },
      { id: "BLO", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "CHW" },
    ],
    name: "Ducky Holmes",
    name_first: "Ducky",
    name_last: "Holmes",
    years: "1895-1905",
    headshot_url: "202307191/images/headshots/9/91ce73fa_sabr.jpg",
    search_name: ["Ducky Holmes"],
    link: "/players/h/holmedu01.shtml",
  },
  {
    id: "honeyc001fre",
    teams: [
      { id: "LAD", season_allstar: 1 },
      { id: "TEX", season_allstar: 1 },
      { id: "NYY" },
      { id: "SEA", season_allstar: 1 },
      { id: "STL" },
      { id: "OAK", ws_champ: 1 },
    ],
    name: "Rick Honeycutt",
    name_first: "Rick",
    name_last: "Honeycutt",
    years: "1977-1997",
    headshot_url: "202307191/images/headshots/f/fc3777de_sabr.jpg",
    search_name: ["Rick Honeycutt"],
    link: "/players/h/honeyri01.shtml",
  },
  {
    id: "hornsb001rog",
    teams: [
      {
        id: "CHC",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_award_mvp: 1,
      },
      {
        id: "SFG",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
      },
      { id: "ATL", season_b_avg_300: 1 },
      { id: "BAL" },
      {
        id: "STL",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_b_hr_40: 1,
        season_award_mvp: 1,
        ws_champ: 1,
      },
    ],
    name: "Rogers Hornsby",
    name_first: "Rogers",
    name_last: "Hornsby",
    years: "1915-1937",
    headshot_url: "202307191/images/headshots/b/b5854fe4_sabr.jpg",
    search_name: ["Rogers Hornsby"],
    link: "/players/h/hornsro01.shtml",
    career_b_avg_300: 1,
    career_award_hof: 1,
  },
  {
    id: "hoskin000wil",
    teams: [
      { id: "MRS", season_allstar: 1 },
      { id: "BEG", season_allstar: 1, season_b_avg_300: 1 },
      { id: "SL2" },
      { id: "NBY", season_allstar: 1 },
      { id: "SEN" },
      { id: "DTS" },
    ],
    name: "Bill Hoskins",
    name_first: "Bill",
    name_last: "Hoskins",
    years: "1937-1946",
    headshot_url: "202307191/images/headshots/3/3be05c11_seamheads.jpg",
    search_name: ["Bill Hoskins"],
    link: "/players/h/hoskibi01.shtml",
  },
  {
    id: "hoy---001wil",
    teams: [
      { id: "LOU", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "WNL", season_b_sb_30: 1 },
      { id: "CIN", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "BFB", season_b_sb_30: 1 },
      { id: "WAS", season_b_sb_30: 1 },
      { id: "STL", season_b_sb_30: 1 },
      { id: "CHW" },
    ],
    name: "Billy Hoy",
    name_first: "Billy",
    name_last: "Hoy",
    years: "1888-1902",
    headshot_url: "202307191/images/headshots/7/763405ef_sabr.jpg",
    search_name: ["Billy Hoy"],
    link: "/players/h/hoydu01.shtml",
  },
  {
    id: "hoyt--001wai",
    teams: [
      { id: "LAD" },
      { id: "PIT" },
      { id: "SFG" },
      { id: "NYY", season_p_w_20: 1, ws_champ: 1 },
      { id: "DET" },
      { id: "OAK" },
      { id: "BOS" },
    ],
    name: "Waite Hoyt",
    name_first: "Waite",
    name_last: "Hoyt",
    years: "1918-1938",
    headshot_url: "202307191/images/headshots/5/5fca5ae6_sabr.jpg",
    search_name: ["Waite Hoyt"],
    link: "/players/h/hoytwa01.shtml",
    career_award_hof: 1,
  },
  {
    id: "hudson001orl",
    teams: [
      { id: "MIN" },
      { id: "ARI", season_allstar: 1, season_award_gold_glove: 1 },
      { id: "LAD", season_allstar: 1, season_award_gold_glove: 1 },
      { id: "SDP" },
      { id: "CHW" },
      { id: "TOR", season_award_gold_glove: 1 },
    ],
    name: "Orlando Hudson",
    name_first: "Orlando",
    name_last: "Hudson",
    years: "2002-2012",
    headshot_url: "202307191/images/headshots/d/df0ac6be_br.jpg",
    search_name: ["Orlando Hudson"],
    link: "/players/h/hudsoor01.shtml",
  },
  {
    id: "hunter002bri",
    teams: [
      { id: "COL" },
      { id: "CIN" },
      { id: "PHI" },
      { id: "SEA", season_b_sb_30: 1 },
      { id: "DET", season_b_sb_30: 1 },
      { id: "HOU", season_b_sb_30: 1 },
    ],
    name: "Brian Hunter",
    name_first: "Brian",
    name_last: "Hunter",
    years: "1994-2003",
    headshot_url: "202307191/images/headshots/2/26a4437a_sabr.jpg",
    search_name: ["Brian Hunter"],
    link: "/players/h/huntebr02.shtml",
  },
  {
    id: "isring001jas",
    teams: [
      { id: "TBD" },
      { id: "NYM" },
      { id: "ANA" },
      { id: "STL", season_allstar: 1, season_p_sv_40: 1 },
      { id: "OAK", season_allstar: 1 },
    ],
    name: "Jason Isringhausen",
    name_first: "Jason",
    name_last: "Isringhausen",
    years: "1995-2012",
    headshot_url: "202307191/images/headshots/4/424ee9c7_sabr.jpg",
    search_name: ["Jason Isringhausen"],
    link: "/players/i/isrinja01.shtml",
    career_p_sv_300: 1,
  },
  {
    id: "jackso002reg",
    teams: [
      {
        id: "ANA",
        season_allstar: 1,
        season_b_rbi_100: 1,
        season_award_silver_slugger: 1,
      },
      {
        id: "NYY",
        season_allstar: 1,
        season_b_rbi_100: 1,
        season_b_hr_40: 1,
        season_award_silver_slugger: 1,
        ws_champ: 1,
      },
      { id: "BAL" },
      {
        id: "OAK",
        season_allstar: 1,
        season_b_rbi_100: 1,
        season_b_hr_40: 1,
        season_award_mvp: 1,
        ws_champ: 1,
      },
    ],
    name: "Reggie Jackson",
    name_first: "Reggie",
    name_last: "Jackson",
    years: "1967-1987",
    headshot_url: "202307191/images/headshots/3/365acf13_sabr-oak.jpg",
    search_name: ["Reggie Jackson"],
    link: "/players/j/jacksre01.shtml",
    career_b_hr_500: 1,
    career_award_hof: 1,
  },
  {
    id: "jenkin001fer",
    teams: [
      { id: "TEX", season_p_w_20: 1, season_p_so_200: 1 },
      {
        id: "CHC",
        season_allstar: 1,
        season_p_w_20: 1,
        season_p_so_200: 1,
        season_award_cy_young: 1,
      },
      { id: "PHI" },
      { id: "BOS" },
    ],
    name: "Fergie Jenkins",
    name_first: "Fergie",
    name_last: "Jenkins",
    years: "1965-1983",
    headshot_url: "202307191/images/headshots/7/7b2f6e52_sabr.jpg",
    search_name: ["Fergie Jenkins"],
    link: "/players/j/jenkife01.shtml",
    career_p_so_3000: 1,
    career_award_hof: 1,
  },
  {
    id: "jenkin000fat",
    teams: [
      { id: "NBY", season_b_avg_300: 1 },
      { id: "NE", season_allstar: 1, season_b_avg_300: 1 },
      { id: "NLG" },
      { id: "HBG", season_b_avg_300: 1 },
      { id: "PS" },
      { id: "BAG", season_b_avg_300: 1 },
      { id: "PC" },
    ],
    name: "Fats Jenkins",
    name_first: "Fats",
    name_last: "Jenkins",
    years: "1924-1940",
    headshot_url: "202307191/images/headshots/3/352a42e4_br.jpg",
    search_name: ["Fats Jenkins"],
    link: "/players/j/jenkifa01.shtml",
  },
  {
    id: "jennin001hug",
    teams: [
      { id: "LOU" },
      { id: "LAD", season_b_sb_30: 1 },
      { id: "PHI" },
      { id: "DET" },
      {
        id: "BLO",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
        season_b_sb_30: 1,
      },
    ],
    name: "Hughie Jennings",
    name_first: "Hughie",
    name_last: "Jennings",
    years: "1891-1918",
    headshot_url: "202307191/images/headshots/c/c9d82d83_sabr.jpg",
    search_name: ["Hughie Jennings"],
    link: "/players/j/jennihu01.shtml",
    career_b_avg_300: 1,
    career_award_hof: 1,
  },
  {
    id: "john--001tho",
    teams: [
      { id: "LAD", season_allstar: 1, season_p_w_20: 1 },
      { id: "ANA" },
      { id: "CLE" },
      { id: "NYY", season_allstar: 1, season_p_w_20: 1 },
      { id: "OAK" },
      { id: "CHW", season_allstar: 1 },
    ],
    name: "Tommy John",
    name_first: "Tommy",
    name_last: "John",
    years: "1963-1989",
    headshot_url: "202307191/images/headshots/c/cb280268_sabr.jpg",
    search_name: ["Tommy John"],
    link: "/players/j/johnto01.shtml",
  },
  {
    id: "johnso002ran",
    teams: [
      {
        id: "ARI",
        season_allstar: 1,
        season_p_w_20: 1,
        season_p_so_200: 1,
        season_award_cy_young: 1,
        ws_champ: 1,
      },
      { id: "WSN" },
      { id: "SFG" },
      { id: "NYY", season_p_so_200: 1 },
      {
        id: "SEA",
        season_allstar: 1,
        season_p_w_20: 1,
        season_p_so_200: 1,
        season_award_cy_young: 1,
      },
      { id: "HOU" },
    ],
    name: "Randy Johnson",
    name_first: "Randy",
    name_last: "Johnson",
    years: "1988-2009",
    headshot_url: "202307191/images/headshots/e/e905e1ef_br.jpg",
    search_name: ["Randy Johnson"],
    link: "/players/j/johnsra05.shtml",
    career_p_w_300: 1,
    career_p_so_3000: 1,
    career_award_hof: 1,
  },
  {
    id: "johnso002hea",
    teams: [
      { id: "MRS" },
      { id: "NWB" },
      { id: "HBG", season_b_avg_300: 1 },
      { id: "KCM", season_b_avg_300: 1, season_b_rbi_100: 1, ws_champ: 1 },
      { id: "LVB" },
      { id: "BBS", season_b_avg_300: 1 },
      { id: "CTG" },
      { id: "SLS" },
    ],
    name: "Heavy Johnson",
    name_first: "Heavy",
    name_last: "Johnson",
    years: "1920-1932",
    headshot_url: "202307191/images/headshots/8/8e72f5d7_br.jpg",
    search_name: ["Heavy Johnson"],
    link: "/players/j/johnshe01.shtml",
  },
  {
    id: "johnso001jud",
    teams: [
      { id: "NYC", season_allstar: 1 },
      { id: "HG" },
      { id: "HIL", season_b_avg_300: 1, ws_champ: 1 },
      { id: "PC", season_allstar: 1 },
    ],
    name: "Judy Johnson",
    name_first: "Judy",
    name_last: "Johnson",
    years: "1923-1936",
    headshot_url: "202307191/images/headshots/5/5c84de56_sr.jpg",
    search_name: ["Judy Johnson"],
    link: "/players/j/johnsju99.shtml",
    career_award_hof: 1,
  },
  {
    id: "jones-002dou",
    teams: [
      { id: "CHC" },
      { id: "CLE", season_allstar: 1, season_p_sv_40: 1 },
      { id: "PHI", season_allstar: 1 },
      { id: "BAL" },
      { id: "HOU", season_allstar: 1 },
      { id: "OAK" },
      { id: "MIL" },
    ],
    name: "Doug Jones",
    name_first: "Doug",
    name_last: "Jones",
    years: "1982-2000",
    headshot_url: "202307191/images/headshots/0/094f0c23_davis.jpg",
    search_name: ["Doug Jones"],
    link: "/players/j/jonesdo01.shtml",
    career_p_sv_300: 1,
  },
  {
    id: "jones-001tod",
    teams: [
      { id: "MIN" },
      { id: "COL" },
      { id: "PHI" },
      { id: "BOS" },
      { id: "CIN" },
      { id: "HOU" },
      { id: "DET", season_allstar: 1, season_p_sv_40: 1 },
      { id: "FLA", season_p_sv_40: 1 },
    ],
    name: "Todd Jones",
    name_first: "Todd",
    name_last: "Jones",
    years: "1993-2008",
    headshot_url: "202307191/images/headshots/5/5ec10c72_sabr.jpg",
    search_name: ["Todd Jones"],
    link: "/players/j/jonesto02.shtml",
    career_p_sv_300: 1,
  },
  {
    id: "jones-018cha",
    teams: [
      { id: "CNR", season_b_avg_300: 1 },
      { id: "ATL", season_b_avg_300: 1 },
      { id: "NYP" },
      { id: "WES" },
      { id: "KCC" },
      { id: "HNA" },
      { id: "CHC" },
      { id: "CIN", season_b_avg_300: 1 },
    ],
    name: "Charley Jones",
    name_first: "Charley",
    name_last: "Jones",
    years: "1875-1888",
    headshot_url: "202307191/images/headshots/8/824610a1_sabr.jpg",
    search_name: ["Charley Jones"],
    link: "/players/j/jonesch01.shtml",
  },
  {
    id: "joyce-001bil",
    teams: [
      { id: "LAD" },
      { id: "BRS", season_b_sb_30: 1 },
      { id: "SFG", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "WAS", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "BWW", season_b_sb_30: 1 },
    ],
    name: "Bill Joyce",
    name_first: "Bill",
    name_last: "Joyce",
    years: "1890-1898",
    headshot_url: "202307191/images/headshots/2/26fc29e0_sabr.jpg",
    search_name: ["Bill Joyce"],
    link: "/players/j/joycebi01.shtml",
  },
  {
    id: "kaat--001jam",
    teams: [
      {
        id: "MIN",
        season_allstar: 1,
        season_p_w_20: 1,
        season_p_so_200: 1,
        season_award_gold_glove: 1,
      },
      { id: "NYY" },
      { id: "PHI", season_award_gold_glove: 1 },
      { id: "STL", ws_champ: 1 },
      {
        id: "CHW",
        season_allstar: 1,
        season_p_w_20: 1,
        season_award_gold_glove: 1,
      },
    ],
    name: "Jim Kaat",
    name_first: "Jim",
    name_last: "Kaat",
    years: "1959-1983",
    headshot_url: "202307191/images/headshots/d/db7b7601_sabr.jpg",
    search_name: ["Jim Kaat"],
    link: "/players/k/kaatji01.shtml",
    career_award_hof: 1,
  },
  {
    id: "kauff-001ben",
    teams: [
      { id: "NEW", season_b_avg_300: 1, season_b_h_200: 1, season_b_sb_30: 1 },
      { id: "SFG", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "BTT", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "NYY" },
    ],
    name: "Benny Kauff",
    name_first: "Benny",
    name_last: "Kauff",
    years: "1912-1920",
    headshot_url: "202307191/images/headshots/4/4a224847_davis.jpg",
    search_name: ["Benny Kauff"],
    link: "/players/k/kauffbe01.shtml",
    career_b_avg_300: 1,
  },
  {
    id: "keefe-002tim",
    teams: [
      { id: "TRT" },
      { id: "NYI" },
      { id: "SFG", season_p_w_20: 1, season_p_so_200: 1 },
      { id: "PHI" },
      { id: "NYP", season_p_w_20: 1, season_p_so_200: 1 },
    ],
    name: "Tim Keefe",
    name_first: "Tim",
    name_last: "Keefe",
    years: "1880-1893",
    headshot_url: "202307191/images/headshots/6/6f1dd1b1_sabr.jpg",
    search_name: ["Tim Keefe"],
    link: "/players/k/keefeti01.shtml",
    career_p_w_300: 1,
    career_award_hof: 1,
  },
  {
    id: "keeler001wil",
    teams: [
      { id: "LAD", season_b_avg_300: 1, season_b_h_200: 1, season_b_sb_30: 1 },
      { id: "SFG" },
      { id: "NYY", season_b_avg_300: 1 },
      { id: "BLO", season_b_avg_300: 1, season_b_h_200: 1, season_b_sb_30: 1 },
    ],
    name: "Willie Keeler",
    name_first: "Willie",
    name_last: "Keeler",
    years: "1892-1910",
    headshot_url: "202307191/images/headshots/0/074d42fd_sabr.jpg",
    search_name: ["Willie Keeler"],
    link: "/players/k/keelewi01.shtml",
    career_b_avg_300: 1,
    career_award_hof: 1,
  },
  {
    id: "keiste001wil",
    teams: [
      { id: "MIN", season_b_avg_300: 1 },
      { id: "PHI", season_b_avg_300: 1 },
      { id: "ATL" },
      { id: "STL", season_b_sb_30: 1 },
      { id: "BLO", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "BLA", season_b_avg_300: 1 },
    ],
    name: "Bill Keister",
    name_first: "Bill",
    name_last: "Keister",
    years: "1896-1903",
    headshot_url: "202307191/images/headshots/9/9f31dbcc_sabr.jpg",
    search_name: ["Bill Keister"],
    link: "/players/k/keistbi01.shtml",
  },
  {
    id: "kell--001geo",
    teams: [
      { id: "BAL", season_allstar: 1 },
      {
        id: "DET",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_h_200: 1,
      },
      { id: "CHW", season_allstar: 1, season_b_avg_300: 1 },
      { id: "BOS", season_allstar: 1, season_b_avg_300: 1 },
      { id: "OAK" },
    ],
    name: "George Kell",
    name_first: "George",
    name_last: "Kell",
    years: "1943-1957",
    headshot_url: "202307191/images/headshots/a/acecef17_sabr.jpg",
    search_name: ["George Kell"],
    link: "/players/k/kellge01.shtml",
    career_b_avg_300: 1,
    career_award_hof: 1,
  },
  {
    id: "kelly-003geo",
    teams: [
      { id: "LAD" },
      { id: "CHC" },
      { id: "CIN", season_b_rbi_100: 1 },
      { id: "PIT" },
      { id: "SFG", season_b_avg_300: 1, season_b_rbi_100: 1, ws_champ: 1 },
    ],
    name: "George Kelly",
    name_first: "George",
    name_last: "Kelly",
    years: "1915-1932",
    headshot_url: "202307191/images/headshots/3/3e4a0c89_sabr.jpg",
    search_name: ["George Kelly"],
    link: "/players/k/kellyge01.shtml",
    career_award_hof: 1,
  },
  {
    id: "kelley002jos",
    teams: [
      { id: "LAD", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "CIN", season_b_avg_300: 1 },
      { id: "PIT" },
      { id: "ATL" },
      {
        id: "BLO",
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_b_sb_30: 1,
      },
      { id: "BLA" },
    ],
    name: "Joe Kelley",
    name_first: "Joe",
    name_last: "Kelley",
    years: "1891-1908",
    headshot_url: "202307191/images/headshots/1/17b00755_sabr.jpg",
    search_name: ["Joe Kelley"],
    link: "/players/k/kellejo01.shtml",
    career_b_avg_300: 1,
    career_award_hof: 1,
  },
  {
    id: "kelly-002kin",
    teams: [
      { id: "CNR", season_b_avg_300: 1 },
      { id: "BRS", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "CHC", season_b_avg_300: 1, season_b_sb_30: 1 },
      { id: "SFG" },
      { id: "CKK" },
      { id: "ATL", season_b_avg_300: 1, season_b_sb_30: 1 },
    ],
    name: "King Kelly",
    name_first: "King",
    name_last: "Kelly",
    years: "1878-1893",
    headshot_url: "202307191/images/headshots/f/ffc40dac_sabr.jpg",
    search_name: ["King Kelly"],
    link: "/players/k/kellyki01.shtml",
    career_b_avg_300: 1,
    career_award_hof: 1,
  },
  {
    id: "kent--001jef",
    teams: [
      {
        id: "LAD",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_award_silver_slugger: 1,
      },
      { id: "NYM" },
      { id: "CLE" },
      {
        id: "SFG",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_rbi_100: 1,
        season_award_silver_slugger: 1,
        season_award_mvp: 1,
      },
      { id: "HOU", season_allstar: 1, season_b_rbi_100: 1 },
      { id: "TOR" },
    ],
    name: "Jeff Kent",
    name_first: "Jeff",
    name_last: "Kent",
    years: "1992-2008",
    headshot_url: "202307191/images/headshots/5/5c319114_sabr.jpg",
    search_name: ["Jeff Kent"],
    link: "/players/k/kentje01.shtml",
  },
  {
    id: "kimbre001cra",
    teams: [
      { id: "LAD" },
      { id: "SDP" },
      { id: "CHC", season_allstar: 1 },
      { id: "PHI", season_allstar: 1 },
      { id: "ATL", season_allstar: 1, season_p_sv_40: 1, season_award_roty: 1 },
      { id: "CHW", season_allstar: 1 },
      { id: "BOS", season_allstar: 1, season_p_sv_40: 1, ws_champ: 1 },
    ],
    name: "Craig Kimbrel",
    name_first: "Craig",
    name_last: "Kimbrel",
    years: "2010-2023",
    headshot_url: "202307191/images/headshots/8/869305cd_mlbam.jpg",
    search_name: ["Craig Kimbrel"],
    link: "/players/k/kimbrcr01.shtml",
    career_p_sv_300: 1,
  },
  {
    id: "king--001sil",
    teams: [
      { id: "KCN" },
      { id: "CIN" },
      { id: "SFG", season_p_w_20: 1 },
      { id: "PIT" },
      { id: "WAS" },
      { id: "STL", season_p_w_20: 1, season_p_so_200: 1 },
      { id: "CHP", season_p_w_20: 1 },
    ],
    name: "Silver King",
    name_first: "Silver",
    name_last: "King",
    years: "1886-1897",
    headshot_url: "202307191/images/headshots/c/cadc5ca0_sabr.jpg",
    search_name: ["Silver King"],
    link: "/players/k/kingsi01.shtml",
  },
  */
  {
    id: "kinsle001ian",
    teams: [
      {
        id: "TEX",
        season_allstar: 1,
        season_b_avg_300: 1,
        season_b_sb_30: 1,
        season_b_hr_30_sb_30: 1,
      },
      { id: "SDP" },
      { id: "ANA", season_award_gold_glove: 1 },
      { id: "DET", season_allstar: 1, season_award_gold_glove: 1 },
      { id: "BOS", season_award_gold_glove: 1, ws_champ: 1 },
    ],
    name: "Ian Kinsler",
    name_first: "Ian",
    name_last: "Kinsler",
    years: "2006-2019",
    headshot_url: "202307191/images/headshots/4/4037c26a_br.jpg",
    search_name: ["Ian Kinsler"],
    link: "/players/k/kinslia01.shtml",
  },
  /*
  {
    id: "konetc001edw",
    teams: [
      { id: "LAD", season_b_avg_300: 1 },
      { id: "PIT" },
      { id: "PHI" },
      { id: "ATL" },
      { id: "PBS", season_b_avg_300: 1 },
      { id: "STL", season_b_avg_300: 1 },
    ],
    name: "Ed Konetchy",
    name_first: "Ed",
    name_last: "Konetchy",
    years: "1907-1921",
    headshot_url: "202307191/images/headshots/c/c6889260_davis.jpg",
    search_name: ["Ed Konetchy"],
    link: "/players/k/koneted01.shtml",
  },
  */
];
